location="Central India"
resource_group_name="dev-RSG"
env = "dev"
aks_client_secret = "VT=uSgbTanZhyz@%nL9Hpd+Tfay_MRV#"
kubernetes_version = "1.21"
admin_username = "azureuser"
system_agents_min_count = "5"
system_agents_max_count = "10"
system_agents_count = 5
system_agents_size = "Standard_D2_v2"
private_subnet_id = "private-subnet-1"
worker_agents_size = "Standard_D2_v2"
worker_agents_min_count = "5"
worker_agents_max_count = "40"
worker_agents_count = "10"
logs_ws_location = "Central India"